//{{NO_DEPENDENCIES}}
#define VERSION_INFO 1
#define IDD_DIALOG1 101
#define IDI_APPICON 103
#define IDS_INTRO 104
#define IDC_TEXT 1001
#define IDC_SEQUENCE 1002

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 106
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1003
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
